/**
 * Provenance Store — persists per-run causal chains and localizes where runs diverge.
 *
 * Lives under the durable `.phoenix/provenance/` namespace (alongside the negative-knowledge store),
 * which is preserved across compaction per PRD §12.1. Storage is two-tier:
 *   - `runs.jsonl`        — append-only ancestry index (one compact RunHeader per line; never deleted)
 *   - `runs/<run_id>.json` — the full RunProvenance record
 * No cold blobs: the record stores hashes + verdicts, not generated bytes (deferred until a consumer
 * needs the bytes). No selective-invalidation read API yet, for the same reason.
 */
import { mkdirSync, writeFileSync, readFileSync, appendFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type {
  RunProvenance, RunHeader, DivergenceReport, DivergenceDetail,
} from '../models/provenance.js';

export interface RunFilter {
  /** Only runs produced by this Phoenix commit — the cross-version comparison filter. */
  phoenix_version?: string;
  trigger_kind?: string;
}

export class ProvenanceStore {
  private runsDir: string;
  private indexPath: string;

  constructor(phoenixRoot: string) {
    const dir = join(phoenixRoot, 'provenance');
    this.runsDir = join(dir, 'runs');
    mkdirSync(this.runsDir, { recursive: true });
    this.indexPath = join(dir, 'runs.jsonl');
  }

  /** Persist a run's provenance: full record + a compact ancestry-index line. */
  record(rp: RunProvenance): void {
    writeFileSync(join(this.runsDir, `${rp.run_id}.json`), JSON.stringify(rp, null, 2), 'utf8');
    const header: RunHeader = {
      run_id: rp.run_id,
      created_at: rp.created_at,
      phoenix_version: rp.producer.phoenix_version,
      trigger_kind: rp.trigger.kind,
      verdict_signature: rp.verdict_signature,
      overall: rp.overall,
      tree_hash: rp.tree_hash,
    };
    appendFileSync(this.indexPath, JSON.stringify(header) + '\n', 'utf8');
  }

  getRun(runId: string): RunProvenance | undefined {
    const p = join(this.runsDir, `${runId}.json`);
    if (!existsSync(p)) return undefined;
    return JSON.parse(readFileSync(p, 'utf8')) as RunProvenance;
  }

  /** Headers from the ancestry index (insertion order, oldest first), optionally filtered. */
  listRuns(filter?: RunFilter): RunHeader[] {
    if (!existsSync(this.indexPath)) return [];
    const headers = readFileSync(this.indexPath, 'utf8')
      .split('\n').filter(Boolean)
      .map(l => JSON.parse(l) as RunHeader);
    return headers.filter(h =>
      (filter?.phoenix_version === undefined || h.phoenix_version === filter.phoenix_version) &&
      (filter?.trigger_kind === undefined || h.trigger_kind === filter.trigger_kind));
  }

  /**
   * Localize where a set of runs' causal chains first fork. Walks stages upstream→downstream and stops
   * at the FIRST that differs — that is the root cause. Works on any run-ids: a within-session set
   * (determinism) or runs tagged with different Phoenix versions (cross-version "did my fix help").
   */
  diffRuns(runIds: string[]): DivergenceReport {
    const runs = runIds
      .map(id => this.getRun(id))
      .filter((r): r is RunProvenance => r !== undefined);

    const verdictSigs = [...new Set(runs.map(r => r.verdict_signature))];
    const report = (stage: DivergenceReport['stage'], details: DivergenceDetail[]): DivergenceReport => ({
      run_ids: runs.map(r => r.run_id),
      stage,
      details,
      verdict_stable: verdictSigs.length <= 1,
      verdict_signatures: verdictSigs,
    });

    if (runs.length < 2) return report('none', []);

    // Stage 1 — inputs (canonicalization, upstream of generation).
    const inputForks = forks(runs, r => {
      const m: Record<string, string> = {
        clause_set: r.inputs.clause_set_hash,
        canonical_graph: r.inputs.canonical_graph_hash,
      };
      for (const [k, v] of Object.entries(r.inputs.contract_hashes ?? {})) m[`contract:${k}`] = v;
      return m;
    });
    if (inputForks.length) return report('inputs', inputForks);

    // Stage 2 — generation (inputs identical; an IU's generated code differs).
    const genForks = forks(runs, r =>
      Object.fromEntries(r.ius.map(iu => [iu.iu_id, iu.generation.code_hash])));
    if (genForks.length) return report('generation', genForks);

    // Stage 3 — evaluation (code identical; an evaluator verdict differs).
    const evalForks = forks(runs, r => {
      const m: Record<string, string> = {};
      for (const c of r.checks) m[`check:${c.name}`] = c.ok ? '1' : '0';
      for (const iu of r.ius) m[iu.iu_id] = iu.decision;
      return m;
    });
    if (evalForks.length) return report('evaluation', evalForks);

    return report('none', []);
  }
}

/** Keys whose value differs across runs (a key absent in a run reads as '∅'). */
function forks(
  runs: RunProvenance[],
  project: (r: RunProvenance) => Record<string, string>,
): DivergenceDetail[] {
  const maps = runs.map(project);
  const keys = new Set<string>();
  for (const m of maps) for (const k of Object.keys(m)) keys.add(k);

  const details: DivergenceDetail[] = [];
  for (const k of keys) {
    const variants = [...new Set(maps.map(m => m[k] ?? '∅'))];
    if (variants.length > 1) details.push({ key: k, variants });
  }
  return details;
}
