/**
 * Runtime Target: node-typescript-express
 *
 * Compiles web-api architecture to Node.js + TypeScript + Express 5.
 * Same architecture, language, and DB driver (better-sqlite3) as
 * `node-typescript`; the only delta is the framework — Express instead
 * of Hono.
 *
 * Why this exists: load-bears the RuntimeTarget abstraction. Iterations
 * 3-6 pulled five Hono-specific assumptions onto RuntimeTarget hooks
 * (mandatoryImports, stripImportPatterns, generateServerEntry,
 * generateModuleStub, generateServiceTests). This target exercises every
 * one of them with a different framework — proving the abstraction is
 * actually load-bearing, not just theoretical.
 */

import type {
  RuntimeTarget,
  RouteWiring,
  ServiceDescriptor,
} from '../models/architecture.js';
import type { ImplementationUnit } from '../models/iu.js';
import { nodeTypescript } from './node-typescript.js';

// ─── Module template (LLM fills in marked sections) ─────────────────────────

const MODULE_TEMPLATE = `import { Router } from 'express';
import type { Request, Response } from 'express';
import { db, registerMigration } from '../../db.js';
import { z } from 'zod';

// ─── Database migrations ────────────────────────────────────────────────────
/* __MIGRATIONS__ */

// ─── Validation schemas ─────────────────────────────────────────────────────
/* __SCHEMAS__ */

// ─── Routes ─────────────────────────────────────────────────────────────────
const router = Router();

/* __ROUTES__ */

export default router;

/* __PHOENIX_METADATA__ */
`;

// ─── Shared files ───────────────────────────────────────────────────────────

const APP_FILE = `import express from 'express';
import type { Request, Response, NextFunction, Router } from 'express';

const app = express();
app.use(express.json());

app.get('/health', (req: Request, res: Response) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

// 4-arg signature marks this as Express's error-handling middleware.
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
  console.error('Unhandled error:', err.message, err.stack);
  res.status(500).json({ error: err.message });
});

export function mount(path: string, router: Router): void {
  app.use(path || '/', router);
}

export { app };
`;

// ─── Server entry generator ─────────────────────────────────────────────────

function generateExpressServerEntry(routes: RouteWiring[]): string {
  const routeImports = routes.map(r => `import ${r.importName} from '${r.importPath}';`);
  const routeMounts = routes.map(r => `mount('${r.mountPath}', ${r.importName});`);
  return [
    `import { app, mount } from './app.js';`,
    `import { runMigrations } from './db.js';`,
    ``,
    `// Generated route modules`,
    ...routeImports,
    ``,
    `// Mount routes`,
    ...routeMounts,
    ``,
    `// JSON 404 fallback — must be after all mounts (Express middleware`,
    `// runs in registration order). Aligns with the Hono target's notFound.`,
    `app.use((_req, res) => { res.status(404).json({ error: 'Not Found' }); });`,
    ``,
    `const port = parseInt(process.env.PORT ?? '3000', 10);`,
    `runMigrations();`,
    `app.listen(port, () => {`,
    `  console.log(\`Server running at http://localhost:\${port}\`);`,
    `});`,
    ``,
  ].join('\n');
}

// ─── Module stub & test scaffold ────────────────────────────────────────────

function generateExpressModuleStub(iu: ImplementationUnit): string {
  return `import { Router } from 'express';
import type { Request, Response } from 'express';

const router = Router();

router.get('/', (_req: Request, res: Response) => {
  res.json({ stub: true, module: '${iu.name}', message: 'Not yet implemented' });
});

export default router;

/** @internal Phoenix VCS traceability — do not remove. */
export const _phoenix = {
  iu_id: '${iu.iu_id}',
  name: '${iu.name}',
  risk_tier: '${iu.risk_tier}',
  canon_ids: [${iu.source_canon_ids.length} as const],
} as const;
`;
}

function generateExpressServiceTests(svc: ServiceDescriptor): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * ${svc.name} — Generated Tests`);
  lines.push(` * AUTO-GENERATED by Phoenix VCS`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import { describe, it, expect } from 'vitest';`);

  for (const mod of svc.modules) {
    const importName = mod.replace('.ts', '').replace(/-/g, '_');
    lines.push(`import ${importName} from '../${mod.replace('.ts', '.js')}';`);
  }

  lines.push(``);
  lines.push(`describe('${svc.name} modules', () => {`);

  for (const mod of svc.modules) {
    const importName = mod.replace('.ts', '').replace(/-/g, '_');
    const displayName = mod.replace('.ts', '').replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    lines.push(`  describe('${displayName}', () => {`);
    // Express's Router() returns a function (callable middleware) with
    // attached methods, so the framework-shaped assertion is on its type.
    lines.push(`    it('exports an Express router as default', () => {`);
    lines.push(`      expect(${importName}).toBeDefined();`);
    lines.push(`      expect(typeof ${importName}).toBe('function');`);
    lines.push(`    });`);
    lines.push(`  });`);
  }

  lines.push(`});`);
  lines.push(``);
  return lines.join('\n');
}

// ─── Prompt extension ───────────────────────────────────────────────────────

const PROMPT_EXTENSION = `
## Runtime: Node.js + TypeScript (Express 5 + better-sqlite3 + Zod)

You are filling in sections of a module template. The imports, router, and exports are already provided.
You MUST output ONLY the content for the marked sections, in this exact format:

\`\`\`
__MIGRATIONS__
registerMigration('tablename', \`
  CREATE TABLE IF NOT EXISTS tablename (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ...columns...
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

__SCHEMAS__
const CreateSchema = z.object({ ... });
const UpdateSchema = z.object({ ... });

__ROUTES__
router.get('/', (req, res) => { ... });
router.post('/', (req, res) => { ... });
router.get('/:id', (req, res) => { ... });
router.patch('/:id', (req, res) => { ... });
router.delete('/:id', (req, res) => { ... });
\`\`\`

### Rules
- Use better-sqlite3 synchronous API: db.prepare(sql).run(), .get(), .all()
- Use parameterized queries ALWAYS — never interpolate user input into SQL
- In SQL, use single quotes for string literals: datetime('now'). NEVER double quotes.
- ALWAYS use snake_case for column names and JSON response keys
- Nullable FK fields: z.number().int().nullable().optional()
- FK validation: if (fk_id != null) { check exists } (loose equality)
- LEFT JOIN to include related resource names (e.g., project_name)
- Query parameter filtering: build WHERE clause dynamically from req.query

### Express conventions (different from Hono!)
- Body access: req.body (express.json() middleware is already applied in app.ts)
- Path params: req.params.id  (string; cast to Number when querying SQL)
- Query params: req.query.foo  (string | undefined)
- JSON response: res.json(obj)
- Status code: res.status(N).json(obj) — chain status() before json()
- 204 No Content: res.status(204).send()
- Always 'return' after sending a response to avoid double-send errors
- Validation pattern:
    const result = CreateSchema.safeParse(req.body);
    if (!result.success) { res.status(400).json({ error: result.error.issues[0].message }); return; }
- 200=read, 201=create, 204=delete, 400=validation, 404=not found
- Do NOT call next() in route handlers; just send the response.

### Web interface modules
- res.send(htmlString) with a complete HTML document
- res.set('Content-Type', 'text/html; charset=utf-8') before res.send if needed
- Use fetch('/resource-name') in client-side JS to call sibling API modules (no /api/ prefix)
- Include ALL CSS and JavaScript inline
`;

// ─── Code examples (few-shot) ───────────────────────────────────────────────

const CODE_EXAMPLES = `
## Example: CRUD module sections for a "notes" resource

\`\`\`
__MIGRATIONS__
registerMigration('notes', \`
  CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    category_id INTEGER REFERENCES categories(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

__SCHEMAS__
const CreateNoteSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().optional().default(''),
  category_id: z.number().int().nullable().optional(),
});

const UpdateNoteSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  body: z.string().optional(),
  category_id: z.number().int().nullable().optional(),
});

__ROUTES__
router.get('/', (req, res) => {
  let sql = 'SELECT notes.*, categories.name as category_name FROM notes LEFT JOIN categories ON notes.category_id = categories.id';
  const conditions: string[] = [];
  const params: unknown[] = [];
  const categoryId = req.query.category_id;
  if (categoryId !== undefined) { conditions.push('notes.category_id = ?'); params.push(Number(categoryId)); }
  if (conditions.length > 0) sql += ' WHERE ' + conditions.join(' AND ');
  sql += ' ORDER BY notes.created_at DESC';
  res.json(db.prepare(sql).all(...params));
});

router.get('/:id', (req, res) => {
  const note = db.prepare('SELECT notes.*, categories.name as category_name FROM notes LEFT JOIN categories ON notes.category_id = categories.id WHERE notes.id = ?').get(req.params.id);
  if (!note) { res.status(404).json({ error: 'Not found' }); return; }
  res.json(note);
});

router.post('/', (req, res) => {
  const result = CreateNoteSchema.safeParse(req.body);
  if (!result.success) { res.status(400).json({ error: result.error.issues[0].message }); return; }
  const { title, body: noteBody, category_id } = result.data;
  if (category_id != null) {
    if (!db.prepare('SELECT id FROM categories WHERE id = ?').get(category_id)) {
      res.status(400).json({ error: 'Category not found' });
      return;
    }
  }
  const info = db.prepare('INSERT INTO notes (title, body, category_id) VALUES (?, ?, ?)').run(title, noteBody, category_id ?? null);
  const note = db.prepare('SELECT notes.*, categories.name as category_name FROM notes LEFT JOIN categories ON notes.category_id = categories.id WHERE notes.id = ?').get(info.lastInsertRowid);
  res.status(201).json(note);
});

router.patch('/:id', (req, res) => {
  const id = req.params.id;
  if (!db.prepare('SELECT id FROM notes WHERE id = ?').get(id)) { res.status(404).json({ error: 'Not found' }); return; }
  const result = UpdateNoteSchema.safeParse(req.body);
  if (!result.success) { res.status(400).json({ error: result.error.issues[0].message }); return; }
  const u = result.data;
  if (u.title !== undefined) db.prepare('UPDATE notes SET title = ? WHERE id = ?').run(u.title, id);
  if (u.body !== undefined) db.prepare('UPDATE notes SET body = ? WHERE id = ?').run(u.body, id);
  if (u.category_id !== undefined) db.prepare('UPDATE notes SET category_id = ? WHERE id = ?').run(u.category_id, id);
  res.json(db.prepare('SELECT notes.*, categories.name as category_name FROM notes LEFT JOIN categories ON notes.category_id = categories.id WHERE notes.id = ?').get(id));
});

router.delete('/:id', (req, res) => {
  const id = req.params.id;
  if (!db.prepare('SELECT id FROM notes WHERE id = ?').get(id)) { res.status(404).json({ error: 'Not found' }); return; }
  db.prepare('DELETE FROM notes WHERE id = ?').run(id);
  res.status(204).send();
});
\`\`\`
`;

// ─── Export ─────────────────────────────────────────────────────────────────

export const nodeTypescriptExpress: RuntimeTarget = {
  name: 'node-typescript-express',
  description: 'Node.js + TypeScript — Express 5, better-sqlite3, Zod',
  language: 'typescript',

  packages: {
    'express': '^5.0.0',
    'better-sqlite3': '^11.7.0',
    'zod': '^3.24.0',
  },

  devPackages: {
    'typescript': '^5.4.0',
    'vitest': '^2.0.0',
    '@types/node': '^22.0.0',
    '@types/express': '^5.0.0',
    '@types/better-sqlite3': '^7.6.0',
    'tsx': '^4.0.0',
  },

  moduleTemplate: MODULE_TEMPLATE,
  promptExtension: PROMPT_EXTENSION,
  codeExamples: CODE_EXAMPLES,

  // Reuse the better-sqlite3 db.ts from node-typescript verbatim (same DB
  // driver), but ship our own Express-flavored app.ts.
  sharedFiles: {
    'src/db.ts': nodeTypescript.sharedFiles['src/db.ts'],
    'src/app.ts': APP_FILE,
  },

  packageExtras: nodeTypescript.packageExtras,

  mandatoryImports: `## MANDATORY: Your module MUST start with these exact imports
\`\`\`
import { Router } from 'express';
import type { Request, Response } from 'express';
import { db, registerMigration } from '../../db.js';
import { z } from 'zod';
\`\`\`
Do NOT call express() directly. Do NOT create a new app instance. Use the Router import above; the shared mount() function in app.ts wires you in.`,

  stripImportPatterns: ['express', 'db.js', 'better-sqlite3', 'zod'],

  generateServerEntry: generateExpressServerEntry,
  generateModuleStub: generateExpressModuleStub,
  generateServiceTests: generateExpressServiceTests,
};
