import { describe, it, expect } from 'vitest';
import { generateIU, generateAll } from '../../src/regen.js';
import { planIUs } from '../../src/iu-planner.js';
import { parseSpec } from '../../src/spec-parser.js';
import { extractCanonicalNodes } from '../../src/canonicalizer.js';

describe('generateIU', () => {
  function makeIU() {
    const clauses = parseSpec('# Auth\n\nUsers must authenticate with email.', 'test.md');
    const canon = extractCanonicalNodes(clauses);
    return planIUs(canon, clauses)[0];
  }

  it('generates files for an IU', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    expect(result.files.size).toBeGreaterThan(0);
  });

  it('generated code contains IU metadata', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    const content = [...result.files.values()][0];
    expect(content).toContain('AUTO-GENERATED by Phoenix VCS');
    expect(content).toContain(iu.iu_id);
    expect(content).toContain(iu.risk_tier);
  });

  it('generated code contains a function stub', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    const content = [...result.files.values()][0];
    expect(content).toContain('export function');
    expect(content).toContain('throw new Error');
  });

  it('produces a manifest with correct file hashes', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    expect(result.manifest.iu_id).toBe(iu.iu_id);

    for (const [path, entry] of Object.entries(result.manifest.files)) {
      expect(entry.content_hash).toHaveLength(64);
      expect(entry.size).toBeGreaterThan(0);
      expect(result.files.has(path)).toBe(true);
    }
  });

  it('records regen metadata', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    const meta = result.manifest.regen_metadata;
    expect(meta.model_id).toBeTruthy();
    expect(meta.toolchain_version).toBeTruthy();
    expect(meta.promptpack_hash).toHaveLength(64);
    expect(meta.generated_at).toBeTruthy();
  });

  it('does not set fell_back when no LLM was configured', async () => {
    const iu = makeIU();
    const result = await generateIU(iu);
    expect(result.manifest.regen_metadata.fell_back).toBeUndefined();
  });

  it('sets fell_back=true when the LLM provider throws', async () => {
    const iu = makeIU();
    const throwingLLM = {
      name: 'fake',
      model: 'thrower',
      generate: async () => { throw new Error('simulated ETIMEDOUT'); },
    };
    const errors: string[] = [];
    const result = await generateIU(iu, {
      llm: throwingLLM,
      canonNodes: extractCanonicalNodes(parseSpec('# Auth\n\nUsers must authenticate.', 'test.md')),
      onProgress: (_iu, status, msg) => { if (status === 'error' && msg) errors.push(msg); },
    });
    expect(result.manifest.regen_metadata.fell_back).toBe(true);
    expect(errors.length).toBeGreaterThan(0);
    expect(errors[0]).toMatch(/simulated ETIMEDOUT/);
  });
});

describe('generateAll', () => {
  it('generates for multiple IUs', async () => {
    const spec = `# Auth\n\nUsers must authenticate.\n\n# Billing\n\nPayments must be processed.`;
    const clauses = parseSpec(spec, 'test.md');
    const canon = extractCanonicalNodes(clauses);
    const ius = planIUs(canon, clauses);
    const results = await generateAll(ius);
    expect(results.length).toBe(ius.length);
  });
});
