/**
 * #30 — "deterministic as measured by the evaluation": the `phoenix verify` gate compares runs by
 * their EVALUATED verdict (order-independent), not by generated bytes. Same verdict → same signature
 * regardless of check/IU ordering; any flip (a check or an IU evidence verdict) → a different signature.
 */
import { describe, it, expect } from 'vitest';
import { verdictSignature } from '../../src/harness/run.js';
import type { RunResult } from '../../src/harness/run.js';

const chk = (name: string, ok: boolean) => ({ name, ok, detail: '' });
const run = (over: Partial<RunResult>): RunResult => ({ ok: true, runId: 'r', ...over });

describe('#30: verdictSignature is order-independent and verdict-sensitive', () => {
  it('identical verdict in any order → identical signature', () => {
    const a = run({
      acceptance: { ok: true, checks: [chk('typecheck', true), chk('ui_behavior', true)] },
      evidence: [{ iu: 'Store', verdict: 'PASS' }, { iu: 'Web', verdict: 'PASS' }],
    });
    const b = run({
      acceptance: { ok: true, checks: [chk('ui_behavior', true), chk('typecheck', true)] },
      evidence: [{ iu: 'Web', verdict: 'PASS' }, { iu: 'Store', verdict: 'PASS' }],
    });
    expect(verdictSignature(a)).toBe(verdictSignature(b));
  });

  it('a flipped acceptance check → different signature (the #32 contract flap)', () => {
    const green = run({ acceptance: { ok: true, checks: [chk('cross-module-contract', true)] } });
    const red = run({ ok: false, failedStage: 'acceptance', acceptance: { ok: false, checks: [chk('cross-module-contract', false)] } });
    expect(verdictSignature(green)).not.toBe(verdictSignature(red));
  });

  it('a flipped per-IU evidence verdict → different signature (the #34 ui_behavior flap)', () => {
    const pass = run({ evidence: [{ iu: 'Web Experience', verdict: 'PASS' }] });
    const fail = run({ evidence: [{ iu: 'Web Experience', verdict: 'FAIL' }] });
    expect(verdictSignature(pass)).not.toBe(verdictSignature(fail));
  });
});
